export enum ChainId {
  // Testnets on which ShibaswapV2 is deployed
  PUPPYNET = 157,
  SEPOLIA = 11155111,
  BNB_TESTNET = 97,
  ARBITRUM_SEPOLIA = 421614,
  OPTIMISM_SEPOLIA = 11155420,
  BASE_SEPOLIA = 84532,
  POLYGON_AMOY = 80002,
  SCROLL_SEPOLIA = 534351,
  LINEA_SEPOLIA = 59141,
  CELO_ALFAJORES = 44787,
  GNOSIS_CHIADO = 10200,
  MANTLE_TESTNET = 5003,
  BLAST_SEPOLIA = 168587773,
  AVALANCHE_FUJI = 43113,

  // Mainnets on which ShibaswapV2 is deployed
  SHIBARIUM = 109,
  MAINNET = 1,
  BNB = 56,
  ARBITRUM_ONE = 42161,
  OPTIMISM = 10,
  BASE = 8453,
  POLYGON = 137,
  SCROLL = 534352,
  LINEA = 59144,
  CELO = 42220,
  GNOSIS = 100,
  MANTLE = 5000,
  BLAST = 81457,
  AVALANCHE = 43114,

  // Yet to deploy ShibaswapV2 ?
  GOERLI = 5,
  OPTIMISM_GOERLI = 420,
  ARBITRUM_GOERLI = 421613,
  POLYGON_MUMBAI = 80001,
  MOONBEAM = 1284,
  BASE_GOERLI = 84531,
  ZORA = 7777777,
  ZORA_SEPOLIA = 999999999,
  ROOTSTOCK = 30
}

export const SUPPORTED_CHAINS = [
  ChainId.PUPPYNET,
  ChainId.SEPOLIA,
  ChainId.BNB_TESTNET,
  ChainId.ARBITRUM_SEPOLIA,
  ChainId.OPTIMISM_SEPOLIA,
  ChainId.BASE_SEPOLIA,
  ChainId.POLYGON_AMOY,
  ChainId.SCROLL_SEPOLIA,
  ChainId.LINEA_SEPOLIA,
  ChainId.CELO_ALFAJORES,
  ChainId.GNOSIS_CHIADO,
  ChainId.MANTLE_TESTNET,
  ChainId.BLAST_SEPOLIA,
  ChainId.AVALANCHE_FUJI,

  ChainId.SHIBARIUM,
  ChainId.MAINNET,
  ChainId.BNB,
  ChainId.ARBITRUM_ONE,
  ChainId.OPTIMISM,
  ChainId.BASE,
  ChainId.POLYGON,
  ChainId.SCROLL,
  ChainId.LINEA,
  ChainId.CELO,
  ChainId.GNOSIS,
  ChainId.MANTLE,
  ChainId.BLAST,
  ChainId.AVALANCHE,

  ChainId.OPTIMISM_GOERLI,
  ChainId.ARBITRUM_GOERLI,

  ChainId.POLYGON_MUMBAI,
  ChainId.GOERLI,

  ChainId.BASE_GOERLI,
  ChainId.ZORA,
  ChainId.ZORA_SEPOLIA,
  ChainId.ROOTSTOCK
] as const
export type SupportedChainsType = typeof SUPPORTED_CHAINS[number]

export enum NativeCurrencyName {
  // Strings match input for CLI
  ETHER = 'ETH',
  MATIC = 'MATIC',
  CELO = 'CELO',
  GNOSIS = 'XDAI',
  MOONBEAM = 'GLMR',
  BNB = 'BNB',
  AVAX = 'AVAX',
  ROOTSTOCK = 'RBTC'
}
